name: chore_bid
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0-323.0.dev

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_auth: ^5.6.2
  cloud_firestore: ^5.6.11
  cloud_functions: ^5.6.1
  shared_preferences: ^2.5.3
  firebase_core: ^3.6.0
  google_fonts: ^6.2.1
  qr_code_scanner: ^1.0.1
  qr_flutter: ^4.1.0
  firebase_messaging: ^15.2.10
  lottie: ^3.1.2
  audioplayers: ^5.2.1
  flutter_animate: ^4.5.0
  confetti: ^0.7.0
  flutter_tts: ^3.8.3

  flutter_localizations:
    sdk: flutter

  # Keep intl only once to avoid duplicate key error.
  # If version solving complains, try bumping to ^0.20.2 with your Flutter version.
  intl: ^0.19.0
  flutter_gen: ^5.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  # Enable ARB-based localization code gen
  generate: true

  uses-material-design: true

  assets:
    - assets/anim/awesome.json
    - assets/anim/confetti.json
